version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    depends_on: 
      - db

  db:
    image: mysql:8.0
    restart: always
    # appleチップでも動くようにする
    platform: linux/x86_64
    environment: 
      MYSQL_DATABASE: event_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - .dbdate:/var/lib/mysql
    ports: 
      - 3306:3306
