# GitHub リポジトリの "Actions" タブに表示されるワークフロー名
name: example-event-app-actions

# ワークフローが実行されるトリガーを定義する
on: push

# ワークフローのジョブを定義する
jobs:
  # ジョブ名
  sample_build:
    # 実行環境
    runs-on: ubuntu-latest # GitHub ホストランナーを使用(無料枠の確認する)
    # アクション
    steps:
        # GitHub リポジトリをチェックアウト
      - uses: actions/checkout@v2
        # ワークスペースの作成
      - name: Run a one-line script
        run: echo Hello, world!
        # フロントエンドのテストを実行
        # frontendディレクトリで依存関係をインストール
      - name: Install dependencies
        run: |
          npm install
          npm install @typescript-eslint/eslint-plugin@latest @typescript-eslint/parser@latest --save-dev
        working-directory: ./frontend
        # frontendディレクトリでESLintを実行
      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
        working-directory: ./frontend

